require 'spec_helper' 

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CallHistoriesController do

  def mock_call_history(stubs={})
    @mock_call_history ||= mock_model(CallHistory, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all call_histories as @call_histories" do
      CallHistory.stub(:all) { [mock_call_history] }
      get :index
      assigns(:call_histories).should eq([mock_call_history])
    end
  end

  describe "GET show" do
    it "assigns the requested call_history as @call_history" do
      CallHistory.stub(:find).with("37") { mock_call_history }
      get :show, :id => "37"
      assigns(:call_history).should be(mock_call_history)
    end
  end

  describe "GET new" do
    it "assigns a new call_history as @call_history" do
      CallHistory.stub(:new) { mock_call_history }
      get :new
      assigns(:call_history).should be(mock_call_history)
    end
  end

  describe "GET edit" do
    it "assigns the requested call_history as @call_history" do
      CallHistory.stub(:find).with("37") { mock_call_history }
      get :edit, :id => "37"
      assigns(:call_history).should be(mock_call_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created call_history as @call_history" do
        CallHistory.stub(:new).with({'these' => 'params'}) { mock_call_history(:save => true) }
        post :create, :call_history => {'these' => 'params'}
        assigns(:call_history).should be(mock_call_history)
      end

      it "redirects to the created call_history" do
        CallHistory.stub(:new) { mock_call_history(:save => true) }
        post :create, :call_history => {}
        response.should redirect_to(call_history_url(mock_call_history))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved call_history as @call_history" do
        CallHistory.stub(:new).with({'these' => 'params'}) { mock_call_history(:save => false) }
        post :create, :call_history => {'these' => 'params'}
        assigns(:call_history).should be(mock_call_history)
      end

      it "re-renders the 'new' template" do
        CallHistory.stub(:new) { mock_call_history(:save => false) }
        post :create, :call_history => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested call_history" do
        CallHistory.stub(:find).with("37") { mock_call_history }
        mock_call_history.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :call_history => {'these' => 'params'}
      end

      it "assigns the requested call_history as @call_history" do
        CallHistory.stub(:find) { mock_call_history(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:call_history).should be(mock_call_history)
      end

      it "redirects to the call_history" do
        CallHistory.stub(:find) { mock_call_history(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(call_history_url(mock_call_history))
      end
    end

    describe "with invalid params" do
      it "assigns the call_history as @call_history" do
        CallHistory.stub(:find) { mock_call_history(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:call_history).should be(mock_call_history)
      end

      it "re-renders the 'edit' template" do
        CallHistory.stub(:find) { mock_call_history(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested call_history" do
      CallHistory.stub(:find).with("37") { mock_call_history }
      mock_call_history.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the call_histories list" do
      CallHistory.stub(:find) { mock_call_history }
      delete :destroy, :id => "1"
      response.should redirect_to(call_histories_url)
    end
  end

end
