require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CallHistoryTypesController do

  def mock_call_history_type(stubs={})
    @mock_call_history_type ||= mock_model(CallHistoryType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all call_history_types as @call_history_types" do
      CallHistoryType.stub(:all) { [mock_call_history_type] }
      get :index
      assigns(:call_history_types).should eq([mock_call_history_type])
    end
  end

  describe "GET show" do
    it "assigns the requested call_history_type as @call_history_type" do
      CallHistoryType.stub(:find).with("37") { mock_call_history_type }
      get :show, :id => "37"
      assigns(:call_history_type).should be(mock_call_history_type)
    end
  end

  describe "GET new" do
    it "assigns a new call_history_type as @call_history_type" do
      CallHistoryType.stub(:new) { mock_call_history_type }
      get :new
      assigns(:call_history_type).should be(mock_call_history_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested call_history_type as @call_history_type" do
      CallHistoryType.stub(:find).with("37") { mock_call_history_type }
      get :edit, :id => "37"
      assigns(:call_history_type).should be(mock_call_history_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created call_history_type as @call_history_type" do
        CallHistoryType.stub(:new).with({'these' => 'params'}) { mock_call_history_type(:save => true) }
        post :create, :call_history_type => {'these' => 'params'}
        assigns(:call_history_type).should be(mock_call_history_type)
      end

      it "redirects to the created call_history_type" do
        CallHistoryType.stub(:new) { mock_call_history_type(:save => true) }
        post :create, :call_history_type => {}
        response.should redirect_to(call_history_type_url(mock_call_history_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved call_history_type as @call_history_type" do
        CallHistoryType.stub(:new).with({'these' => 'params'}) { mock_call_history_type(:save => false) }
        post :create, :call_history_type => {'these' => 'params'}
        assigns(:call_history_type).should be(mock_call_history_type)
      end

      it "re-renders the 'new' template" do
        CallHistoryType.stub(:new) { mock_call_history_type(:save => false) }
        post :create, :call_history_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested call_history_type" do
        CallHistoryType.stub(:find).with("37") { mock_call_history_type }
        mock_call_history_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :call_history_type => {'these' => 'params'}
      end

      it "assigns the requested call_history_type as @call_history_type" do
        CallHistoryType.stub(:find) { mock_call_history_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:call_history_type).should be(mock_call_history_type)
      end

      it "redirects to the call_history_type" do
        CallHistoryType.stub(:find) { mock_call_history_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(call_history_type_url(mock_call_history_type))
      end
    end

    describe "with invalid params" do
      it "assigns the call_history_type as @call_history_type" do
        CallHistoryType.stub(:find) { mock_call_history_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:call_history_type).should be(mock_call_history_type)
      end

      it "re-renders the 'edit' template" do
        CallHistoryType.stub(:find) { mock_call_history_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested call_history_type" do
      CallHistoryType.stub(:find).with("37") { mock_call_history_type }
      mock_call_history_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the call_history_types list" do
      CallHistoryType.stub(:find) { mock_call_history_type }
      delete :destroy, :id => "1"
      response.should redirect_to(call_history_types_url)
    end
  end

end
