require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LocalsController do

  def mock_local(stubs={})
    @mock_local ||= mock_model(Local, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all locals as @locals" do
      Local.stub(:all) { [mock_local] }
      get :index
      assigns(:locals).should eq([mock_local])
    end
  end

  describe "GET show" do
    it "assigns the requested local as @local" do
      Local.stub(:find).with("37") { mock_local }
      get :show, :id => "37"
      assigns(:local).should be(mock_local)
    end
  end

  describe "GET new" do
    it "assigns a new local as @local" do
      Local.stub(:new) { mock_local }
      get :new
      assigns(:local).should be(mock_local)
    end
  end

  describe "GET edit" do
    it "assigns the requested local as @local" do
      Local.stub(:find).with("37") { mock_local }
      get :edit, :id => "37"
      assigns(:local).should be(mock_local)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created local as @local" do
        Local.stub(:new).with({'these' => 'params'}) { mock_local(:save => true) }
        post :create, :local => {'these' => 'params'}
        assigns(:local).should be(mock_local)
      end

      it "redirects to the created local" do
        Local.stub(:new) { mock_local(:save => true) }
        post :create, :local => {}
        response.should redirect_to(local_url(mock_local))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved local as @local" do
        Local.stub(:new).with({'these' => 'params'}) { mock_local(:save => false) }
        post :create, :local => {'these' => 'params'}
        assigns(:local).should be(mock_local)
      end

      it "re-renders the 'new' template" do
        Local.stub(:new) { mock_local(:save => false) }
        post :create, :local => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested local" do
        Local.stub(:find).with("37") { mock_local }
        mock_local.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :local => {'these' => 'params'}
      end

      it "assigns the requested local as @local" do
        Local.stub(:find) { mock_local(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:local).should be(mock_local)
      end

      it "redirects to the local" do
        Local.stub(:find) { mock_local(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(local_url(mock_local))
      end
    end

    describe "with invalid params" do
      it "assigns the local as @local" do
        Local.stub(:find) { mock_local(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:local).should be(mock_local)
      end

      it "re-renders the 'edit' template" do
        Local.stub(:find) { mock_local(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested local" do
      Local.stub(:find).with("37") { mock_local }
      mock_local.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the locals list" do
      Local.stub(:find) { mock_local }
      delete :destroy, :id => "1"
      response.should redirect_to(locals_url)
    end
  end

end
