require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StatusTicketsController do

  def mock_status_ticket(stubs={})
    @mock_status_ticket ||= mock_model(StatusTicket, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all status_tickets as @status_tickets" do
      StatusTicket.stub(:all) { [mock_status_ticket] }
      get :index
      assigns(:status_tickets).should eq([mock_status_ticket])
    end
  end

  describe "GET show" do
    it "assigns the requested status_ticket as @status_ticket" do
      StatusTicket.stub(:find).with("37") { mock_status_ticket }
      get :show, :id => "37"
      assigns(:status_ticket).should be(mock_status_ticket)
    end
  end

  describe "GET new" do
    it "assigns a new status_ticket as @status_ticket" do
      StatusTicket.stub(:new) { mock_status_ticket }
      get :new
      assigns(:status_ticket).should be(mock_status_ticket)
    end
  end

  describe "GET edit" do
    it "assigns the requested status_ticket as @status_ticket" do
      StatusTicket.stub(:find).with("37") { mock_status_ticket }
      get :edit, :id => "37"
      assigns(:status_ticket).should be(mock_status_ticket)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created status_ticket as @status_ticket" do
        StatusTicket.stub(:new).with({'these' => 'params'}) { mock_status_ticket(:save => true) }
        post :create, :status_ticket => {'these' => 'params'}
        assigns(:status_ticket).should be(mock_status_ticket)
      end

      it "redirects to the created status_ticket" do
        StatusTicket.stub(:new) { mock_status_ticket(:save => true) }
        post :create, :status_ticket => {}
        response.should redirect_to(status_ticket_url(mock_status_ticket))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved status_ticket as @status_ticket" do
        StatusTicket.stub(:new).with({'these' => 'params'}) { mock_status_ticket(:save => false) }
        post :create, :status_ticket => {'these' => 'params'}
        assigns(:status_ticket).should be(mock_status_ticket)
      end

      it "re-renders the 'new' template" do
        StatusTicket.stub(:new) { mock_status_ticket(:save => false) }
        post :create, :status_ticket => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested status_ticket" do
        StatusTicket.stub(:find).with("37") { mock_status_ticket }
        mock_status_ticket.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :status_ticket => {'these' => 'params'}
      end

      it "assigns the requested status_ticket as @status_ticket" do
        StatusTicket.stub(:find) { mock_status_ticket(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:status_ticket).should be(mock_status_ticket)
      end

      it "redirects to the status_ticket" do
        StatusTicket.stub(:find) { mock_status_ticket(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(status_ticket_url(mock_status_ticket))
      end
    end

    describe "with invalid params" do
      it "assigns the status_ticket as @status_ticket" do
        StatusTicket.stub(:find) { mock_status_ticket(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:status_ticket).should be(mock_status_ticket)
      end

      it "re-renders the 'edit' template" do
        StatusTicket.stub(:find) { mock_status_ticket(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested status_ticket" do
      StatusTicket.stub(:find).with("37") { mock_status_ticket }
      mock_status_ticket.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the status_tickets list" do
      StatusTicket.stub(:find) { mock_status_ticket }
      delete :destroy, :id => "1"
      response.should redirect_to(status_tickets_url)
    end
  end

end
