require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TicketTypeGroupsController do

  def mock_ticket_type_group(stubs={})
    @mock_ticket_type_group ||= mock_model(TicketTypeGroup, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ticket_type_groups as @ticket_type_groups" do
      TicketTypeGroup.stub(:all) { [mock_ticket_type_group] }
      get :index
      assigns(:ticket_type_groups).should eq([mock_ticket_type_group])
    end
  end

  describe "GET show" do
    it "assigns the requested ticket_type_group as @ticket_type_group" do
      TicketTypeGroup.stub(:find).with("37") { mock_ticket_type_group }
      get :show, :id => "37"
      assigns(:ticket_type_group).should be(mock_ticket_type_group)
    end
  end

  describe "GET new" do
    it "assigns a new ticket_type_group as @ticket_type_group" do
      TicketTypeGroup.stub(:new) { mock_ticket_type_group }
      get :new
      assigns(:ticket_type_group).should be(mock_ticket_type_group)
    end
  end

  describe "GET edit" do
    it "assigns the requested ticket_type_group as @ticket_type_group" do
      TicketTypeGroup.stub(:find).with("37") { mock_ticket_type_group }
      get :edit, :id => "37"
      assigns(:ticket_type_group).should be(mock_ticket_type_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ticket_type_group as @ticket_type_group" do
        TicketTypeGroup.stub(:new).with({'these' => 'params'}) { mock_ticket_type_group(:save => true) }
        post :create, :ticket_type_group => {'these' => 'params'}
        assigns(:ticket_type_group).should be(mock_ticket_type_group)
      end

      it "redirects to the created ticket_type_group" do
        TicketTypeGroup.stub(:new) { mock_ticket_type_group(:save => true) }
        post :create, :ticket_type_group => {}
        response.should redirect_to(ticket_type_group_url(mock_ticket_type_group))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket_type_group as @ticket_type_group" do
        TicketTypeGroup.stub(:new).with({'these' => 'params'}) { mock_ticket_type_group(:save => false) }
        post :create, :ticket_type_group => {'these' => 'params'}
        assigns(:ticket_type_group).should be(mock_ticket_type_group)
      end

      it "re-renders the 'new' template" do
        TicketTypeGroup.stub(:new) { mock_ticket_type_group(:save => false) }
        post :create, :ticket_type_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ticket_type_group" do
        TicketTypeGroup.stub(:find).with("37") { mock_ticket_type_group }
        mock_ticket_type_group.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ticket_type_group => {'these' => 'params'}
      end

      it "assigns the requested ticket_type_group as @ticket_type_group" do
        TicketTypeGroup.stub(:find) { mock_ticket_type_group(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ticket_type_group).should be(mock_ticket_type_group)
      end

      it "redirects to the ticket_type_group" do
        TicketTypeGroup.stub(:find) { mock_ticket_type_group(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ticket_type_group_url(mock_ticket_type_group))
      end
    end

    describe "with invalid params" do
      it "assigns the ticket_type_group as @ticket_type_group" do
        TicketTypeGroup.stub(:find) { mock_ticket_type_group(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ticket_type_group).should be(mock_ticket_type_group)
      end

      it "re-renders the 'edit' template" do
        TicketTypeGroup.stub(:find) { mock_ticket_type_group(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ticket_type_group" do
      TicketTypeGroup.stub(:find).with("37") { mock_ticket_type_group }
      mock_ticket_type_group.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ticket_type_groups list" do
      TicketTypeGroup.stub(:find) { mock_ticket_type_group }
      delete :destroy, :id => "1"
      response.should redirect_to(ticket_type_groups_url)
    end
  end

end
